### ISSUE TITLE
Collect "sync/singleflight"'s shared result bool as metrics

### ISSUE THREAD

**Issue by jcjones** [letsencrypt/ctile#10]
It'd be pretty cool as a follow-on to collect arg3 here (`shared bool`) for metrics.

_Originally posted by @jcjones in https://github.com/letsencrypt/ctile/pull/9#discussion_r1312473245_

**Comment by jmhodges** [comment]
Whatever metrics solution is used in #6 should probably also be used for this

**Comment by jsha** [comment]
We're gonna do Prometheus! PRs welcome.
